### PR TITLE
Add check that port can be used on current platform

### PR DESCRIPTION
**Pull request by kurthindenburg**
Implement a check that the current platform is in the port's
platforms list.

This only handles the current platforms statement in the Portfile.

see https://trac.macports.org/ticket/15712

### CODE REVIEW

**Comment by kurthindenburg** [comment]
This is a WIP to see if this is how we want to do this.  This can be committed as-is or we can wait until I figure out all the conditionals in the trac ticket.  I'll also have to a lot of tests to verify it all works.

A wrong platform will error out before the arch check.

Note: the _mportexec check is for the dependencies install.

**Comment by pmetzger** [comment]
Does this handle things like `platforms    {darwin >=8}` ?

**Comment by jmroot** [comment]
No, it doesn't. This should not be merged in its current form because it does not handle `platforms macosx` correctly, and because we don't want all ports to error out on non-darwin platforms anyway. We should be looking at which platforms are known not to work, rather than which ones are not known to work.

**Comment by kurthindenburg** [comment]
I don't think I understand exactly what needs done here so I'll close this for now.

**Comment by pmetzger** [comment]
I think what was being asked for was the ability to specify conditionals describing which platforms and os versions to build or not to build on. We do desperately need a facility like this, though.

**Comment by pmetzger** [comment]
The question isn't one of "did the maintainer test it". I have ports like OCaml that I know do not run on certain OSes but I get build errors for them anyway every time I touch them, which creates noise and confusion and wastes time on the build systems. The goal is to stop trying to build on things where we know building will not work and can never work. There are a lot of such things.

**Comment by danielluke** [comment]
Ok. Making life easier for maintainer / macports-build infrastructure related and not a feature for end-users.

I think we just shouldn't bother building stuff for so many (old/non-supported/not being updated) OS releases.

**Comment by pmetzger** [comment]
That's another argument to be had. For now, I'd like to mark that OCaml can't build on 10.4 and 10.5.

**Pull request closed without merging**
