### PR TITLE
portindex: support creating PortIndex for libc++

### PR DESCRIPTION
**Pull request by mojca**
I'm submitting @ryandesign's patch from https://trac.macports.org/ticket/55471 for easier review and testing. 

It would be great to see it deployed soon. For that to happen another minor patch is needed, see the ticket.

### CODE REVIEW

**Comment by pmetzger** [comment]
1. Looks like there's been no comment after several weeks.
2. The patch now has a conflict.

**Comment by mojca** [comment]
1. There was a lot of subsequent discussion going on in the ticket linked above. This is what happens when you mix tickets and PRs (and this is why we have issues disabled).
2. The conflict seems trivial to resolve and I can do that, but after I submitted this PR and did some more testing I figured out there were further changes needed as it didn't work as intended. The changes needed are not that hard to make either.

**Comment by mojca** [comment]
@ryandesign: can you please check the changes I made?
I would prefer adding a few tests for this to the base, but I'm not sure how.

**Comment by pmetzger** [comment]
@ryandesign Thoughts? Do you think we can integrate this?

**Comment by pmetzger** [comment]
@ryandesign Just another ping, I know you've been having trouble keeping up with your email.

**Comment by ryandesign** [comment]
I supplied my comments in the ticket earlier.

**Comment by mojca** [comment]
Since #83 has been merged, I'm closing this. We should probably finish the discussion in the ticket and then simply commit the remaining changes.

**Pull request closed without merging**
