### PR TITLE
Specify missing `void` parameter in function declarators

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Fixes: https://trac.macports.org/ticket/68320

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
See https://github.com/macports/macports-base/pull/301#issuecomment-1783645161 regarding CI failure.

**Review by raimue — APPROVED** [review]
Looks good to me. But I did not try to confirm whether this caught all warnings of this kind.

**Comment by chrstphrchvz** [comment]
> Looks good to me. But I did not try to confirm whether this caught all warnings of this kind.

Currently, this PR does not address all `-Wstrict-prototypes` warnings. It only tries to deal with any which MacPorts itself would be responsible for. There are plenty more in vendor (Tcl, etc.) and autoconf tests; should this PR instead deal with those as well?

Also, this would only resolves warnings seen in `make all` and the macOS 13 build log the ticket referred to; I have not combed through the code to see if that missed any others (e.g. not compiled or hidden from the compiler).

**Comment by chrstphrchvz** [comment]
Added fix for the one -Wstrict-prototypes warning seen during the Tcl 8.6.13 build. It will probably be accepted by upstream for Tcl 8.6.14.

**Comment by raimue** [comment]
> Currently, this PR does not address all `-Wstrict-prototypes` warnings. It only tries to deal with any which MacPorts itself would be responsible for. There are plenty more in vendor (Tcl, etc.) and autoconf tests; should this PR instead deal with those as well?

I agree if we need it, we should try to submit this upstream if they did not already address this. Then sync it with a new upstream version. Just as you did now. :smiley: 

Our patches to the vendored sources should be kept minimal and only apply build fixes we absolutely need. And vendored code throws other warnings as well.

**Pull request merged**
