### PR TITLE
port1.0: configure: Add check for implicit decls

### PR DESCRIPTION
**Pull request by neverpanic**
On macOS 11, implicit function declarations are now errors by default. This may affect configure checks and actually cause software to compile differently without us knowing.

Add a post-configure check that scans any `config.log` files in `${configure.dir}` for indicators of such problems and warn about them, so they will not go unnoticed.

Provide a way to disable this functionality in a Portfile, in case the maintainer did verify that those are false positives.

### CODE REVIEW

**Comment by ryandesign** [comment]
Good idea. I'll test this.

**Review by ryandesign — APPROVED** [review]
Seems to work. And we do need to make it easier to see these types of errors. But it's going to point out soooooo many errors that we need to fix. ☹️☹️☹️

**Comment by ryandesign** [comment]
And then there will be ports like freetds where it reports:
```
Warning:   conftest.c:152:16: error: implicit declaration of function 'gethostbyname_r' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```
`gethostbyname_r` is not available on macOS, so it is fine that the configure script checks for it and doesn't find it.

I can add `configure.checks.implicit_function_declaration no` but won't that mean that I'll miss out on any new implicit declaration of function errors introduced by future versions of freetds?

**Comment by neverpanic** [comment]
> And then there will be ports like freetds where it reports:
> 
> ```
> Warning:   conftest.c:152:16: error: implicit declaration of function 'gethostbyname_r' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
> ```
> 
> `gethostbyname_r` is not available on macOS, so it is fine that the configure script checks for it and doesn't find it.
> 
> I can add `configure.checks.implicit_function_declaration no` but won't that mean that I'll miss out on any new implicit declaration of function errors introduced by future versions of freetds?

Yes. We should probably extract the function names it checks for, and provide both a global and a local whitelist. Otherwise this may just cause way too many warnings to be useful?

**Comment by neverpanic** [comment]
@ryandesign Would you please try again with this version? I believe that should be sufficiently tweak-able that we can quickly hide the false positives.

**Comment by neverpanic** [comment]
@ryandesign I haven't upgraded to Big Sur yet, so I'd like to get feedback before merging this.

**Comment by ryandesign** [comment]
I haven't upgraded to Big Sur either, but I fake it by modifying MacPorts base as follows:
```
--- src/port1.0/portconfigure.tcl.orig
+++ src/port1.0/portconfigure.tcl
         configure.classpath
 # compiler flags section
 default configure.optflags      -Os
-default configure.cflags        {${configure.optflags}}
-default configure.objcflags     {${configure.optflags}}
+default configure.cflags        {${configure.optflags} -Werror=implicit-function-declaration}
+default configure.objcflags     {${configure.optflags} -Werror=implicit-function-declaration}
 default configure.cppflags      {[portconfigure::configure_get_cppflags]}
 proc portconfigure::configure_get_cppflags {} {
     global prefix
```
This at least works for ports that honor MacPorts CFLAGS.

**Comment by neverpanic** [comment]
@ryandesign Thanks, that's helpful. I've tested running configure on my ports with this and am satisfied with the result. I'll wait for CI to pass and merge this afterwards.

**Pull request merged**
