### PR TITLE
portindex: return >0 value if some ports failed

### PR DESCRIPTION
**Pull request by l2dy**
https://trac.macports.org/wiki/Meetings/MacPortsMeeting2018/GSoC#Hackingsessionideas

### CODE REVIEW

**Comment by l2dy** [comment]
@raimue Can you check the failing test? I'm still on my way home from the meeting.

**Comment by raimue** [comment]
I can only assume that `portindex` in this test already failed on this port before, but the error was silently ignored, in which case this change was a good idea to detect it.

The error can be reproduced by running `portindex` on an empty Portfile.

**Comment by raimue** [comment]
Should be fixed as of e97d916d.

**Comment by jmroot** [comment]
I still think this may cause problems elsewhere. For example, `port sync` will now print an error saying "updating PortIndex for $source failed" if some ports failed to parse, which is not entirely true and may alarm users. The fact that some ports failed to parse is already reported by portindex itself.

I really think someone needs to review all the places that portindex is used if this is going to be the default behaviour. And we would need to inform users that their own scripts may break.

Another problem is that there's no distinction between some portfiles failing to parse and portindex failing entirely due to e.g. lack of permissions.

**Comment by danielluke** [comment]
If no one wants to review every place portindex is used (and/or if we don't want to communicate this out to users and deal with any support issues from the behavior change for them) - this could be implemented with an optional command line argument (sort of the inverse of port's -p).

**Comment by jmroot** [comment]
See https://lists.macports.org/pipermail/macports-users/2018-March/044842.html

**Comment by l2dy** [comment]
>See https://lists.macports.org/pipermail/macports-users/2018-March/044842.html

The sync command still returns 0.

**Comment by raimue** [comment]
As I understand it, @jmroot wants to be able to differentiate between fatal errors and errors while parsing some ports. This is reasonable, as in this state it would not even update `PortIndex.quick` when `portindex` failed. `port sync` not reflecting any error in the exit code is a different issue.

portindex could have different exit codes that base can interpret (for example 1 for fatal error, 2 for failed parsing of some ports).

Or we go with the suggestion made in https://github.com/macports/macports-base/pull/64#issuecomment-373532033. For example, a `portindex -e` flag that causes portindex to return a non-zero exit code when parsing of some ports failed.

**Comment by l2dy** [comment]
Should I change the return code to 2 for now?

**Pull request merged**
