### PR TITLE
Enable cURL's automatic decompression

### PR DESCRIPTION
**Pull request by dgilman**
This closes https://trac.macports.org/ticket/55011 .

### CODE REVIEW

**Comment by ryandesign** [comment]
Thank you, but could you please adjust the whitespace of your changes? Your changes use 3 spaces for indentation. MacPorts standard coding style is 4 spaces for indentation, but these files still largely use tabs for indentation. So please either use tabs for indentation to match the rest of the file, or use 4 spaces for each indent of your changes, and we can detab the rest of the file later in a separate commit.

**Comment by dgilman** [comment]
Oops

**Comment by raimue** [comment]
This change looks good to me. Thanks!

Please follow [CommitMessages](https://trac.macports.org/wiki/CommitMessages) for the commit message format. Add a `Closes:` to the footer with a reference to the Trac ticket.

**Comment by dgilman** [comment]
Anything else needs to be done to get this across the finish line?

**Comment by raimue** [comment]
As there were no objections, I merged this. Thanks for your contribution!

**Comment by jmroot** [comment]
Tests are failing on 10.7 and older after this commit.
https://build.macports.org/builders/base-10.6_x86_64/builds/662
https://build.macports.org/builders/base-10.7_x86_64/builds/662

**Comment by raimue** [comment]
Unfortunately, that test output does not tell anything at all about what failed. I guess it needs someone with access to 10.7 to debug that.

**Pull request merged**
