### PR TITLE
Merge Libsolv (gsoc15-dependency) branch with master

### PR DESCRIPTION
**Pull request by JacksonIsaac**
Merge libsolv branch (from GSoC 2015) with master.

Libsolv is a SAT Solver for dependency calculation and currently supports search, installation and conflict resolution. Libsolv can be used by passing "-l" option to port.

It uses libsolv submodule (fork of upstream to work with Make).

Would like to merge it with master before new season of GSoC begins or there may be merge conflicts or difficulty in updating master while trying to merge multiple projects later on. Also users would be able to contribute and test libsolv from the master copy. Can be in Beta ?

For usage and installation instructions: https://trac.macports.org/wiki/SummerOfCode2015Libsolv

### CODE REVIEW

**Comment by mojca** [comment]
Thank you, I just wanted to ask what the status of your project was and how much was still missing to make it fully functional.

(I wonder if it's possible to make the history of merging somewhat more linear - bearing in mind that making it completely linear is not feasible anyway.)

One option would be to put the code to a branch of `macports-base` in the short term, at least for the sake of the buildbot checking whether it builds everywhere. It would be slightly suboptimal if this year's students would start with broken code :) :) :)

How many more changes are needed before this code could end up in a release?

**Comment by JacksonIsaac** [comment]
@mojca There is a branch in macports-base already, although not updated with latest changes; there were some merge conflicts. I was playing with merge and rebase on my local fork in order to keep the original branch safe from any mishap.

Initially I thought I would finish up uninstall and variant support then open PR with master but as new gsoc is fast approaching I didn't want to risk waiting any longer. Also didn't want to have more merge conflicts, particularly with port migrate project since it will have more hacking on the base.

**Comment by pmetzger** [comment]
This has been sitting in the queue for quite a while, which is a shame. What can we do to get it integrated?

**Comment by JacksonIsaac** [comment]
I am hoping we could get a beta version of libsolv merged with installation, search and conflict resolution support.

Things pending are uninstallation and variants support. We may also need to add or modify portindex at some point of time later, but we can still use portindex as it is for now.

**Comment by pmetzger** [comment]
So if this isn't ready to merge, would it be better to close this and re-open it later when you're feeling ready?

**Comment by JacksonIsaac** [comment]
Yes, that was my plan actually. I'll close the PR with this comment and open a new one with recent changes.

**Pull request closed without merging**
