### PR TITLE
Don't abort if the current folder doesn't exist, use user home.

### PR DESCRIPTION
**Pull request by kurthindenburg**
closes https://trac.macports.org/ticket/40035

### CODE REVIEW

**Comment by kurthindenburg** [comment]
I notice none of the other uses of [pwd] are "caught" for errors.

**Comment by jmroot** [comment]
Also the original pwd (if valid) needs to be saved for use in get_current_port. That's another good reason not to use the home dir, just in case it contains a Portfile.

**Comment by raimue** [comment]
macports1.0 should not mess with the current working directory on loading. For commands like `portindex` that would be unexpected and could make them work, when they should have failed. I think it is better to solve this in the port client.

In most cases, we do not need to initialize `$current_portdir` on startup and that would avoid the problem. We should delay getting cwd until it is actually needed in `proc process_command_file` or `proc process_cmd`). However, we need to make sure `[pwd]` is only evaluated once to get the path the command was started in.

**Comment by jmroot** [comment]
I see your point, but as Kurt pointed out, there are a lot of places throughout the code base where [pwd] is used assuming it won't throw an error (usually in order to cd somewhere else and then cd back afterwards). All of these need to be fixed to really address the issue the ticket brings up.

**Comment by pmetzger** [comment]
Should we close this?

**Comment by kurthindenburg** [comment]
Well I don't think there was a consensus on how to proceed with these [pwd] issues.

**Comment by pmetzger** [comment]
@kurthindenburg Well, given the lack of consensus and the passage of eight months, perhaps this should be closed? The PR queue is really for things that are imminently awaiting integration. If something hasn't gotten consensus after a long time it probably is not going to be integrated soon.

**Pull request closed without merging**
