### PR TITLE
Add migrate action to port command (gsoc-17)

### PR DESCRIPTION
**Pull request by umeshksingla**
I'm creating this PR to move this project forward. It obviously needs plenty many improvements and reviews before it is merged or even thought to be merged. I have been very busy lately. I can provide most of the explanations and invite all types of suggestions to improve it, first the correctness and gradually taking it to meet the standards.

### CODE REVIEW

**Comment by neverpanic** [comment]
@umeshksingla: I rebased this on top of the current master and fixed a few minor issues with the intention of trying this soon during my own migration. Do you mind if I force-push over gsoc17-migrate, or should I push to a different branch or my fork instead?

**Comment by umeshksingla** [comment]
@neverpanic I don't see any problem with you force-pushing some minor changes. But I suggest trying it on a non-primary copy first or creating some test-copy.

**Comment by neverpanic** [comment]
Sure, I'll do that. If all else fails, I can always do migration manually from a list of ports, so I'm not too worried.

**Comment by neverpanic** [comment]
See #56, which supersedes this.

**Pull request closed without merging**
