### PR TITLE
Treat command.env as a list

### PR DESCRIPTION
**Pull request by jmroot**
The previous behaviour involved a complicated regex, made it very
difficult to set an environment variable value including quote
characters, and was responsible for many cases of variables being in
foo.env but not actually appearing in the environment.

Portfiles will need to be reviewed for cases of writing `foo.env-append VAR="foo bar"` since that adds two elements to foo.env, `VAR="foo` and `bar"` (double quotes only have a special meaning to Tcl if they appear at the start of a word).

### CODE REVIEW

**Comment by Ionic** [comment]
> made it very difficult to set an environment variable value including quote characters

If I understood the old regexp correctly, this is an understatement. It was impossible to have ANY quote character be part of the value, unless immediately followed by the first detected quoting character.

Something like:
`FOO="bar'"`
would have worked, while
`FOO="bar'baz"`
would have not matched the regexp in the first place, ignoring the entry and others after it. No way to get around that.


We should also make very clear that this will break backwards compatibility.

It's not just Portfile that used `...env FOO="bar baz"`, but also `...env FOO=\"bar baz\"` and probably other variations.

**Comment by jmroot** [comment]
If you mean in terms of number of affected portfiles, there are currently 991 that contain `.env` and will need to be reviewed. Likely only a fraction of those will need changes, but it's reasonably common among ports that don't use a configure script and pass CFLAGS etc to a Makefile via the environment.

**Comment by jmroot** [comment]
I've started reviewing the portfiles and adding changes conditional on the base version where necessary (and removing some overquoting that was never needed). Once I'm done I'll push the portfile changes and merge this at the same time.

**Comment by neverpanic** [comment]
Right, thanks for looking into it. Should we merge this PR then?

**Comment by jmroot** [comment]
Things will break for anyone running master if this is merged and not the portfile changes. So I would want to merge both at close to the same time.

**Pull request merged**
