### PR TITLE
tracelib.c: Removed unnecessary condition in if

### PR DESCRIPTION
**Pull request by MihirLuthra**
if ((kev.flags & EV_ERROR) == 0 || ((kev.flags & EV_ERROR) > 0 && kev.data != 0))
If compilers find first operand true while evaluating || , the second operand isn’t checked.
So the second operand is only checked if (kev.flags & EV_ERROR) != 0.
So (kev.flags & EV_ERROR) > 0  it doesn’t need to be checked in conjunction with kev.data != 0.
It doesn’t return negative.(tested)

### CODE REVIEW

**Comment by jmroot** [comment]
Please rebase your branch. https://trac.macports.org/wiki/WorkingWithGit#upstream-fetch

**Comment by jmroot** [comment]
> It doesn’t return negative.(tested)

To determine this by testing, you would have to generate every possible error condition and see what is returned. I really doubt you did that. :)

Fortunately, you don't actually have to test because flags is a uint16_t and thus can't be negative by definition.

**Comment by jmroot** [comment]
One more thing: this pattern is repeated in a few other places in the file. Why not change all of them?

**Comment by MihirLuthra** [comment]
On Mon, 1 Apr 2019, 07:35 Joshua Root, <notifications@github.com> wrote:

> It doesn’t return negative.(tested)
>
> To determine this by testing, you would have to generate every possible
> error condition and see what is returned. I really doubt you did that. :)
>
> Fortunately, you don't actually have to test because flags is a uint16_t
> and thus can't be negative by definition.
>
Glad u told me that uint16_t. ^_^

i tried to research there types but cudnt really find.
By tested, i didn't mean like that.

There is already no handling for negative case even if it arises.
Also there are only three flags being formed in there EV_ADD, EV_RECEIPT &
EV_ERROR. I just researched on them. and pretty much combination of these 3
just give arise to 8 conditions.

That is a what i meant to say.

Sorry if i was wrong, i will take more care from next time.

Regards,
Mihir

**Comment by MihirLuthra** [comment]
On Mon, 1 Apr 2019, 07:38 Joshua Root, <notifications@github.com> wrote:

> One more thing: this pattern is repeated in a few other places in the
> file. Why not change all of them?
>
> To be honest, i noticed that now.
I will rebase my branch and change it if it makes sense. :)

Regards
Mihir

**Comment by jmroot** [comment]
> Glad u told me that uint16_t. ^_^
> i tried to research there types but cudnt really find.

If you look at the kevent man page, it refers to a few headers, one of which is sys/event.h. That contains the definition of struct kevent.

**Comment by MihirLuthra** [comment]
Aah, srry for that. My mistake! That didn't come to my attention.
Will be more careful next time.

**Comment by jmroot** [comment]
No need to apologise. This is meant to be a learning experience after all. :)

**Comment by MihirLuthra** [comment]
> No need to apologise. This is meant to be a learning experience after all. :)

Thanks ^_^,
I will rebase my branch and submit a new PR :)

**Comment by jmroot** [comment]
Oh, there should be no need for a new PR. If you update your fork with the commits from macports/macports-base, the PR will update automatically.

One note: the usual GitHub procedure would be to create a new branch in your fork for each PR, and then delete the branch after the PR is merged. That way you can keep master in your fork the same as master in our repo.

**Comment by MihirLuthra** [comment]
Thanks for the helpful info, I will do exactly that. :)

Mihir

>

**Pull request closed without merging**
